# Generated by Django 3.0.8 on 2020-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='名前')),
                ('password1', models.CharField(max_length=100, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'loginuser',
            },
        ),
        migrations.CreateModel(
            name='SignUpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='名前')),
                ('email', models.EmailField(max_length=100, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'upuser',
            },
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='singnupuser',
        ),
    ]
