# Generated by Django 3.0.8 on 2020-07-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='メールアドレス')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'singnupuser',
            },
        ),
    ]
