# Generated by Django 3.0.8 on 2020-07-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200721_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='password1',
            new_name='password',
        ),
    ]
